export const images = {
  xetMiY: require('./images/xetmiy.png'),
  phoMaiLat: require('./images/phomailat.jpg'),
  phoMaiSoi: require('./images/phomaisoi.jpg'),
  xetTanChay: require('./images/tanchay.jpg'),
  xetTruyenThong: require('./images/truyenthong.jpg'),
  xucXich: require('./images/xucxich.jpg'),
  xaLach: require('./images/xa-lach.jpg'),
  gaPopcorn: require('./images/ga-popcorn.jpg'),
  xetAiCap: require('./images/xet-ai-cap.jpg'),
  xetNhenNhen: require('./images/xet-nhen-nhen.jpg'),
  xetZombie: require('./images/xet-zombie.jpg'),
  vietqr: require('./images/vietqr.png'),
  momo: require('./images/momo.png'),
  cash: require('./images/cash.png'),
  momoQr: require('./images/momo-qr.jpg'),
  mongtay: require('./images/mongtay.jpg'),
};
